name: test

on:
  # On push
  push:

  # On pull request
  pull_request:

  # Runs daily at UTC midnight.
  schedule:
    - cron: "0 0 * * *"

  # Allow manual activations.
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, macos-15-intel, windows-latest]
        vscode-version: ["1.85.0", "stable"]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash # Explicitly use Bash on all platforms

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json" # Detects from engines.node

      # Install the node version management. 
      # This sets a script at ~/.nvm/nvm.sh that need to be sourced
      # by any bash instance to define the 'nvm' command.
      - name: Install and configure nvm
        run: |
          set -x
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          find ~/.nvm

      - name: Run lint
        run: |
          set -x
          ./scripts/lint.sh

      - name: Init test environment
        run: |
          ./scripts/init-test-env.sh

      - name: List directories
        run: |
          pwd
          ls -al
          ls -al .vscode-test
          ls -al .vscode-test/workspace

      - name: Run tests
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            # On Ubuntu we need to run headless.
            xvfb-run -a ./scripts/test.sh ${{ matrix.vscode-version }}
          else
            ./scripts/test.sh ${{ matrix.vscode-version }}
          fi
