name: test

on:
  # On push
  push:

  # On pull request
  pull_request:

  # Runs daily at UTC midnight.
  schedule:
    - cron: "0 0 * * *"

  # Allow manual activations.
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        vscode-version: ["1.85.0", "stable"]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash # Explicitly use Bash on all platforms

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json" # Detects from engines.node

      # Node version management. Scripts like lint.sh expect it.
      # Any use of nvm which is a bash script require sourcing it
      # as done below.
      - name: Install and configure nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

          # Source nvm in this step and export for subsequent steps
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

          # Verify installation
          nvm --version

      - name: Run lint
        run: |
          ./scripts/lint.sh

      - name: Init test environment
        run: |
          ./scripts/init-test-env.sh

      - name: List directories
        run: |
          pwd
          ls -al
          ls -al .vscode-test
          ls -al .vscode-test/workspace

      - name: Run tests
        run: |
          if [ "${{ runner.os }}" = "Linux" ]; then
            # On Ubuntu we need to run headless.
            xvfb-run -a ./scripts/test.sh ${{ matrix.vscode-version }}
          else
            ./scripts/test.sh ${{ matrix.vscode-version }}
          fi
